[variables]
NODE_ENV = "production"
NIXPACKS_PATH = "/app"
NPM_CONFIG_PRODUCTION = "true"
NPM_CONFIG_CACHE = "/tmp/.npm"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --no-fund --omit=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run preview -- --host 0.0.0.0 --port 4173"